(in-package :tr.gen.core.server.test)

(deftest-parser crlf? core-server::crlf? (format nil "~%") t)
(deftest-parser lwsp? core-server::lwsp? (format nil "~t") t)
(deftest-parser hex-value? core-server::hex-value? "FA" 250)
(deftest-parser escaped? core-server::escaped? "%fa" 250)
(deftest-parser digit-value? core-server::digit-value? "4" 4)
(deftest-parser fixnum? core-server::fixnum? "424142" 424142)
(deftest-parser version? core-server::version? "1.2.3.4" '(1 2 3 4))
(deftest-parser quoted? core-server::quoted? "\"Here we go\"" "Here we go")

(deftest-render char! core-server::char! #\A "A")
(deftest-render string! core-server::string! "Hello, world!" "Hello, world!")
(deftest-render fixnum! core-server::fixnum! 343 "343")
(deftest-render quoted! core-server::quoted! "Hello, world!" "\"Hello, world!\"")
(deftest-render quoted-fixnum! core-server::quoted-fixnum! 343 "\"343\"")
