(in-package :core-ffi)

;;;-----------------------------------------------------------------------------
;;; ERROR HANDLING ROUTINES FOR KERNEL CALLS
;;;-----------------------------------------------------------------------------
(eval-when (:compile-toplevel :load-toplevel)
  (defvar +error-symbols+ (make-hash-table :test #'eq)))

(eval-when (:compile-toplevel :load-toplevel)
  (defmacro deferrno (symbol errno docstring)
    `(progn
       (defvar ,symbol ,errno ,docstring)
       (setf (gethash ,errno +error-symbols+) ',symbol)
       ',symbol)))

;;;-----------------------------------------------------------------------------
;;; UNIX ERROR CODES
;;;-----------------------------------------------------------------------------
;;; fixme: get those values from grovel.
(deferrno +ECFFI+       -1 "Can't get errno from CFFI")
(deferrno +EPERM+        1 "Operation not permitted")
(deferrno +ENOENT+       2 "No such file or directory")
(deferrno +ESRCH+        3 "No such process")
(deferrno +EINTR+        4 "Interrupted system call")
(deferrno +EIO+          5 "I/O error")
(deferrno +ENXIO+        6 "No such device or address")
(deferrno +E2BIG+        7 "Argument list too long")
(deferrno +ENOEXEC+      8 "Exec format error")
(deferrno +EBADF+        9 "Bad file number")
(deferrno +ECHILD+      10 "No child processes")
(deferrno +EAGAIN+      11 "Try again")
(deferrno +ENOMEM+      12 "Out of memory")
(deferrno +EACCES+      13 "Permission denied")
(deferrno +EFAULT+      14 "Bad address")
(deferrno +ENOTBLK+     15 "Block device required")
(deferrno +EBUSY+       16 "Device or resource busy")
(deferrno +EEXIST+      17 "File exists")
(deferrno +EXDEV+       18 "Cross-device link")
(deferrno +ENODEV+      19 "No such device")
(deferrno +ENOTDIR+     20 "Not a directory")
(deferrno +EISDIR+      21 "Is a directory")
(deferrno +EINVAL+      22 "Invalid argument")
(deferrno +ENFILE+      23 "File table overflow")
(deferrno +EMFILE+      24 "Too many open files")
(deferrno +ENOTTY+      25 "Not a typewriter")
(deferrno +ETXTBSY+     26 "Text file busy")
(deferrno +EFBIG+       27 "File too large")
(deferrno +ENOSPC+      28 "No space left on device")
(deferrno +ESPIPE+      29 "Illegal seek")
(deferrno +EROFS+       30 "Read-only file system")
(deferrno +EMLINK+      31 "Too many links")
(deferrno +EPIPE+       32 "Broken pipe")
(deferrno +EDOM+        33 "Math argument out of domain of func")
(deferrno +ERANGE+      34 "Math result not representable")
(deferrno +EDEADLK+     35 "Resource deadlock would occur")
(deferrno +ENAMETOOLONG+ 36 "File name too long")
(deferrno +ENOLCK+      37 "No record locks available")
(deferrno +ENOSYS+      38 "Function not implemented")
(deferrno +ENOTEMPTY+   39 "Directory not empty")
(deferrno +ELOOP+       40 "Too many symbolic links encountered")
(deferrno +EWOULDBLOCK+ +EAGAIN+ "Operation would block")
(deferrno +ENOMSG+      42 "No message of desired type")
(deferrno +EIDRM+       43 "Identifier removed")
(deferrno +ECHRNG+      44 "Channel number out of range")
(deferrno +EL2NSYNC+    45 "Level 2 not synchronized")
(deferrno +EL3HLT+      46 "Level 3 halted")
(deferrno +EL3RST+      47 "Level 3 reset")
(deferrno +ELNRNG+      48 "Link number out of range")
(deferrno +EUNATCH+     49 "Protocol driver not attached")
(deferrno +ENOCSI+      50 "No CSI structure available")
(deferrno +EL2HLT+      51 "Level 2 halted")
(deferrno +EBADE+       52 "Invalid exchange")
(deferrno +EBADR+       53 "Invalid request descriptor")
(deferrno +EXFULL+      54 "Exchange full")
(deferrno +ENOANO+      55 "No anode")
(deferrno +EBADRQC+     56 "Invalid request code")
(deferrno +EBADSLT+     57 "Invalid slot")
(deferrno +EDEADLOCK+   +EDEADLK+ "Resource deadlock would occur")
(deferrno +EBFONT+      59 "Bad font file format")
(deferrno +ENOSTR+      60 "Device not a stream")
(deferrno +ENODATA+     61 "No data available")
(deferrno +ETIME+       62 "Timer expired")
(deferrno +ENOSR+       63 "Out of streams resources")
(deferrno +ENONET+      64 "Machine is not on the network")
(deferrno +ENOPKG+      65 "Package not installed")
(deferrno +EREMOTE+     66 "Object is remote")
(deferrno +ENOLINK+     67 "Link has been severed")
(deferrno +EADV+        68 "Advertise error")
(deferrno +ESRMNT+      69 "Srmount error")
(deferrno +ECOMM+       70 "Communication error on send")
(deferrno +EPROTO+      71 "Protocol error")
(deferrno +EMULTIHOP+   72 "Multihop attempted")
(deferrno +EDOTDOT+     73 "RFS specific error")
(deferrno +EBADMSG+     74 "Not a data message")
(deferrno +EOVERFLOW+   75 "Value too large for defined data type")
(deferrno +ENOTUNIQ+    76 "Name not unique on network")
(deferrno +EBADFD+      77 "File descriptor in bad state")
(deferrno +EREMCHG+     78 "Remote address changed")
(deferrno +ELIBACC+     79 "Can not access a needed shared library")
(deferrno +ELIBBAD+     80 "Accessing a corrupted shared library")
(deferrno +ELIBSCN+     81 ".lib section in a.out corrupted")
(deferrno +ELIBMAX+     82 "Attempting to link in too many shared libraries")
(deferrno +ELIBEXEC+    83 "Cannot exec a shared library directly")
(deferrno +EILSEQ+      84 "Illegal byte sequence")
(deferrno +ERESTART+    85 "Interrupted system call should be restarted")
(deferrno +ESTRPIPE+    86 "Streams pipe error")
(deferrno +EUSERS+      87 "Too many users")
(deferrno +ENOTSOCK+    88 "Socket operation on non-socket")
(deferrno +EDESTADDRREQ+ 89 "Destination address required")
(deferrno +EMSGSIZE+    90 "Message too long")
(deferrno +EPROTOTYPE+  91 "Protocol wrong type for socket")
(deferrno +ENOPROTOOPT+ 92 "Protocol not available")
(deferrno +EPROTONOSUPPORT+ 93 "Protocol not supported")
(deferrno +ESOCKTNOSUPPORT+ 94 "Socket type not supported")
(deferrno +EOPNOTSUPP+  95 "Operation not supported on transport endpoint")
(deferrno +EPFNOSUPPORT+ 96 "Protocol family not supported")
(deferrno +EAFNOSUPPORT+ 97 "Address family not supported by protocol")
(deferrno +EADDRINUSE+  98 "Address already in use")
(deferrno +EADDRNOTAVAIL+ 99 "Cannot assign requested address")
(deferrno +ENETDOWN+    100 "Network is down")
(deferrno +ENETUNREACH+ 101 "Network is unreachable")
(deferrno +ENETRESET+   102 "Network dropped connection because of reset")
(deferrno +ECONNABORTED+ 103 "Software caused connection abort")
(deferrno +ECONNRESET+  104 "Connection reset by peer")
(deferrno +ENOBUFS+     105 "No buffer space available")
(deferrno +EISCONN+     106 "Transport endpoint is already connected")
(deferrno +ENOTCONN+    107 "Transport endpoint is not connected")
(deferrno +ESHUTDOWN+   108 "Cannot send after transport endpoint shutdown")
(deferrno +ETOOMANYREFS+ 109 "Too many references: cannot splice")
(deferrno +ETIMEDOUT+   110 "Connection timed out")
(deferrno +ECONNREFUSED+ 111 "Connection refused")
(deferrno +EHOSTDOWN+   112 "Host is down")
(deferrno +EHOSTUNREACH+ 113 "No route to host")
(deferrno +EALREADY+    114 "Operation already in progress")
(deferrno +EINPROGRESS+ 115 "Operation now in progress")
(deferrno +ESTALE+      116 "Stale NFS file handle")
(deferrno +EUCLEAN+     117 "Structure needs cleaning")
(deferrno +ENOTNAM+     118 "Not a XENIX named type file")
(deferrno +ENAVAIL+     119 "No XENIX semaphores available")
(deferrno +EISNAM+      120 "Is a named type file")
(deferrno +EREMOTEIO+   121 "Remote I/O error")
(deferrno +EDQUOT+      122 "Quota exceeded")
(deferrno +ENOMEDIUM+   123 "No medium found")
(deferrno +EMEDIUMTYPE+ 124 "Wrong medium type")
(deferrno +ECANCELED+   125 "Operation Canceled")
(deferrno +ENOKEY+      126 "Required key not available")
(deferrno +EKEYEXPIRED+ 127 "Key has expired")
(deferrno +EKEYREVOKED+ 128 "Key has been revoked")
(deferrno +EKEYREJECTED+ 129 "Key was rejected by service")
(deferrno +EOWNERDEAD+  130 "Owner died")
(deferrno +ENOTRECOVERABLE+ 131 "State not recoverable")

;;;-----------------------------------------------------------------------------
;;; ERRNO VARIABLE a.k.a. extern int errno;
;;;-----------------------------------------------------------------------------
;;; fixme: doesn't work with linux/sbcl-1.x
(defcvar ("errno" errno) :int)

(defun errno ()
  #+sbcl (sb-alien:get-errno)
  #-sbcl (if (eq 1 (pointer-address (get-var-pointer '+errno+))) -1 +errno+))

;;;-----------------------------------------------------------------------------
;;; KERNEL ERROR CONDITION FOR PROPER HANDLING
;;;-----------------------------------------------------------------------------
(define-condition kernel-error (error)
  ((errno :initarg :errno :reader kernel-error.errno))
  (:report 
   (lambda (c stream)
     (format stream "Kernel error: ~A:~D:~A"
	     (gethash (kernel-error.errno c) +error-symbols+)
	     (kernel-error.errno c)
	     (documentation 
	      (gethash (kernel-error.errno c) +error-symbols+) 'variable))))
  (:documentation "Signalled when the kernel call ret a negative value."))

(defmethod eagain? ((c kernel-error))
  (eq +EAGAIN+ (kernel-error.errno c)))

;;;-----------------------------------------------------------------------------
;;; PROPER CFFI RETURN TYPE FOR KERNEL CALLS
;;;-----------------------------------------------------------------------------
(defmethod translate-from-foreign (value retval)
  (if (minusp value)
      (error 'kernel-error :errno (errno))
      value))

;; (defmacro %ret (form)
;;   (with-unique-names (errno ret)
;;     `(let ((,ret ,form))
;;        (if (plusp ,ret)
;; 	   ,ret
;; 	   (let ((,errno #+sbcl (sb-alien:get-errno)
;; 			 #-sbcl 0))
;; 	     (error "Kernel error! errno:~D ~A" ,errno		
;; 		    #+sbcl (documentation (gethash (sb-alien:get-errno) +error-symbols+) 'variable)
;; 		    #-sbcl nil))))))